name: Deploy to Production

on:
  push:
    branches:
      - main  # Запускати workflow тільки при push в гілку main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Використовувати віртуальну машину з Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Або інша версія Node.js

      - name: Install dependencies
        run: sudo npm install

      - name: Build project
        run: sudo npm run build

      - name: Install PM2
        run: sudo npm install pm2 -g

      - name: Restart PM2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ http://34.118.21.89/ }}
          username: ${{ pelexach12 }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 restart cd-test


