name: Deploy to Production

on:
  push:
    branches:
      - main  # Запускати workflow тільки при push в гілку main

permissions:
  contents: read
  
jobs:

  deploy:
    runs-on: ubuntu-latest  # Використовувати віртуальну машину з Ubuntu

    steps:

      - name: Restart PM2 process
        uses: appleboy/ssh-action@master
        with:
          host: 34.118.21.89
          username: pelexach12
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/test-automate/ci-cd-test-repo # Замініть на шлях до вашого проекту
            sudo chown -R pelexach12:pelexach12 /var/www/test-automate/ci-cd-test-repo
            git pull origin main
            sudo chown -R root:root /var/www/test-automate/ci-cd-test-repo
            sudo npm install
            sudo npm run build
            pm2 restart cd-test


